site_name: AI-EMS

nav: 

    - Project case study.: 
        - Problem description.: problem description.md
        - Solution context.: solution context.md
    - Getting started.: index.md
    - Model conception.: 
        - Data pre-processing.: data pre-processing.md
        - Model policy.: managment policy.md
    - Contribution: 
        - Contribution guide.: contr_guide.md
    - About.: 
        - Authors.: authors.md
        - Changelog & Versionning.: chng_log.md


markdown_extensions:
    - toc:
        permalink: true  


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme: readthedocs